name: Update M3U Playlist

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次
  push:
    branches:
      - main

jobs:
  update-m3u:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install requests

    - name: Run the script
      run: |
        sed -i '$c\#Generated at $(date "+%Y-%m-%d %H:%M:%S")' processed_itv_proxy.m3u
        python script.py

    - name: List files for debug
      run: ls -al

    - name: Configure Git
      run: |
        git config --global user.name 'freefrank'
        git config --global user.email 'freefrank21@gmail.com'

    - name: Commit changes
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        git add processed_itv_proxy.m3u
        git commit -m 'Update  processed_itv_proxy.m3u'
        git push https://${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git main
